//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployersTable
    {
        public int Id { get; set; }
        public string Payment_method { get; set; }
        public Nullable<decimal> Total { get; set; }
        public int OrderID { get; set; }
    }
}
